app.py
from flask import Flask, redirect, url_for, request
from config import Conf
from flask_sqlalchemy import SQLAlchemy
import sqlite3


from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

from flask_security import current_user
from flask_login import LoginManager

### Инициализация приложения ###

app = Flask(__name__)
app.config.from_object(Conf)

### Создание БД ###

db = SQLAlchemy(app)

### Создание курсосра и соединения с БД ###

conn = sqlite3.connect(r"data/db.db")
cursor = conn.cursor()

login_manager = LoginManager(app)
login_manager.setup_app(app)

### Миграции ###
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

### Админка ###
from mod import *

# class AdminView(ModelView):
#
#     def is_accessible(self):
#         return login.current_user.is_admin
#
#     def inaccessible_callback(self, name, **kwargs):
#         # redirect to login page if user doesn't have access
#         return redirect(url_for('login', next=request.url))

admin = Admin(app)
# admin.add_view(AdminView(Post, db.session))
# admin.add_view(AdminView(User, db.session))
# admin.add_view(AdminView(Tag, db.session))

admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Tag, db.session))

main.py
from app import app


from posts.blueprint import posts
from users.blueprint import users


### Регистрация Blueprint-ов ###

app.register_blueprint(posts, url_prefix='/posts')
app.register_blueprint(users, url_prefix='/users')

### Админка ###
# admin.add_view(ModelView(User, db.session))
# admin.add_view(ModelView(Post, db.session))



### Запуск приложения ###

if __name__ == '__main__':
    app.run(host='')

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, Response, json
from app import app, db
from PIL import Image
from mod import Post, Picture, Tag, Comment, User, user_likes
import os
from werkzeug.utils import secure_filename
from flask_login import current_user


posts = Blueprint('posts', __name__, template_folder='templates')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@posts.route('/')
def index():
    page = request.args.get('page')
    
    q = request.args.get('q')

    if q:
        post = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        post = Post.query.order_by(Post.createDate.desc())


    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
     
    pages = post.paginate(page=page, per_page=15)

    return render_template('posts/index.html', post=post, pages=pages)


@posts.route('/create', methods=['GET', 'POST'])
def create_post():
    tags = Tag.query.all()
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        file = request.files['file']

        user = current_user

        for t in request.form.getlist('tags'):
            tag = Tag.query.filter(Tag.name == t).first()

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            file_prev= Image.open(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            file_prev.save(os.path.join(app.config['UPLOAD_FOLDER'] + '\\post_prev', filename), quality=15,optimize=True)


            pic = Picture(name = filename)
            db.session.add(pic)
            db.session.commit()

            try:
                post = Post(title=title, body=body, likes=0)
                post.pictures.append(pic)
                post.tags.append(tag)
                post.user.append(user)

                db.session.add(post)
                db.session.commit()
            except:
                return 'Something wrong!'
        return redirect(url_for('posts.index'))
    else:
        return render_template('posts/create_post.html', tags=tags)

# @posts.route('/<slug>')
# def post_detail(slug):
#     post = Post.query.filter(Post.slug == slug).first_or_404()
#     tags = post.tags
#
#     return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/<id>')
def post_detail(id):
    post = Post.query.filter(Post.id == id).first_or_404()
    tags = post.tags

    if current_user.is_authenticated:
        user = current_user
        query = user_likes.query.filter(user_likes.u_id == user.id, user_likes.p_id == post.id).first()
        if query:
            is_like_set = True
        else:
            is_like_set = False
    else:
        is_like_set = False

    return render_template('posts/post_detail.html', post=post, tags=tags, is_like_set=is_like_set)

@posts.route('/<id>/add_like')
def add_like(id):
    post = Post.query.filter(Post.id == id).first_or_404()
    user = current_user

    if current_user.is_authenticated:
        query = user_likes.query.filter(user_likes.p_id == post.id, user_likes.u_id == user.id).first()
        if query:
            post.likes -= 1
            db.session.delete(query)
            is_like_set = False
        else:
            post.likes += 1
            row=user_likes(u_id=user.id, p_id=post.id)
            db.session.add(row)
            is_like_set = True
        db.session.commit()
    else:
        is_like_set = False
    response = {
        "likes" : post.likes,
        "is_like_set" : is_like_set,
    }

    return json.dumps(response)

@posts.route('/<id>/add_comment', methods=['GET', 'POST'])
def add_comment(id):
    if current_user:
        post = Post.query.filter(Post.id == id).first_or_404()
        user = current_user

        for i in user.avatar:
            ava = str(i)

        text_comment = request.args.getlist("text")
        current_comment = Comment(text=text_comment[0])
        current_comment.author.append(user)
        post.comment.append(current_comment)
        print(text_comment)
        print(current_user)
        db.session.add(current_comment)

        db.session.commit()
        response = {
            'nickname': user.nickname,
            'userAvatar': ava,
        }
        return json.dumps(response)

 

@posts.route('/tag/<slug>')
def tag_detail(slug):
    page = request.args.get('page')

    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts


    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = posts.paginate(page=page, per_page=15)

    return render_template('posts/tag_detail.html', tag=tag, posts=posts, pages=pages)


# @posts.route('/')
# def index():
#     page = request.args.get('page')
#
#     q = request.args.get('q')
#
#     if q:
#         post = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
#     else:
#         post = Post.query.order_by(Post.createDate.desc())
#
#     if page and page.isdigit():
#         page = int(page)
#     else:
#         page = 1
#
#     pages = post.paginate(page=page, per_page=15)
#
#     return render_template('posts/index.html', post=post, pages=pages)

users/blueprint.py
from flask import Blueprint, render_template
from mod import User
from flask_login import current_user


users = Blueprint('users', __name__, template_folder='templates')

@users.route('/')
def index():
    users = User.query.all()
    return render_template('users/index.html', users=users)

@users.route('/<slug>')
def user_profile(slug):
    u  = User.query.filter(User.slug == slug).first()
    return render_template('users/user_profile.html', user_profile=u)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Создание поста
{% endblock %}

{% block content_title %}
    Создать пост
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <input type="text" name="title" placeholder="Title" style="width: 30%;" required>
            </div>
            <div class="form-group">
                <textarea type="text" class="form-control" name="body" placeholder="Body" style="width: 60%;"
                          required></textarea>
            </div>
            <div class="form-group">
                <input type="file" name="file" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Категория:</label>
                <select class="form-control" name="tags" style="width:100px;" required>
                    {% for t in tags %}
                        <option value="{{ t }}">{{ t }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-success">Create post!</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Посты
{% endblock %}

{% block content_title %}
    Новые посты:
{% endblock %}

{% block content %}
    <div class="content mt-3">
        <div class="row" style="padding: 0px 20px;">
            <div class="card-columns">
                {% for p in pages.items %}
                    <a href="{{ url_for('posts.post_detail', id = p.id) }}">
                        {% for i in p.pictures %}
                            <div class="card">
                                <img src="{{ url_for('static', filename='img/post_prev/' +  i.name) }}" class="img-fluid">
                            </div>
                        {% endfor %}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>


    <nav>
        <ul class="pagination">
            <li {% if not pages.has_prev: %} class="d-none" {% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {% for page in pages.iter_pages() %}
                <li {% if page == pages.page %} class="page-item active" {% endif %}>
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
            {% endfor %}

            <li {% if not pages.has_next %} class="d-none" {% endif %}>
                <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>


{% endblock %}

posts/templates/posts/somethingHTML.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TestHTML</title>
</head>
<body>

</body>
</html>

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}

    <div class="row" style="padding: 0px 20px;">
        <div class="card-columns">
            {% for post in pages.items %}
                <a href="{{ url_for('posts.post_detail', id = post.id) }}">
                    {% for picture in post.pictures %}
                        <div class="card">
                            <img src="{{ url_for('static', filename='img/' +  picture.name) }}" class="img-fluid">
                        </div>
                    {% endfor %}
                </a>
            {% endfor %}
        </div>
    </div>


    <nav>
        <ul class="pagination">
            <li {% if not pages.has_prev: %} class="d-none" {% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {% for page in pages.iter_pages() %}
                <li {% if page == pages.page %} class="page-item active" {% endif %}>
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
            {% endfor %}

            <li {% if not pages.has_next %} class="d-none" {% endif %}>
                <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    {#    {% for p in posts %}#}
    {#        <div>#}
    {#            <a href=" {{ url_for('posts.post_detail', id=p.id) }}">{{ p.title }}</a>#}
    {#        </div>#}
    {#    {% endfor %}#}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">


    {#    <link rel="stylesheet" href="{{ url_for('static', filename='css/jcrop.css') }}">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/media.css') }}">

    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>


<body>
{#------------------------------------------------------------------------------#}


<nav class="navbar navbar-dark for-medium">


    <div class="row flex-grow-1" id="main-menu">
        <div class="col-5"></div>
        <div class="icon-title d-flex col-2">
            <a class="navbar-brand mr-auto " href="/posts" style="color: #15acc5;">
                {#                <img src="{{ url_for('static', filename='img/icons/ArtStart.svg') }}"#}
                {#                     class="img-fluid" alt="" style="height: 80px;">#}
                <strong>ArtStart</strong>
            </a>
        </div>
        <div class="col-5"></div>


        <div class="col-12" id="search">
            <form class="form d-flex align-items-center">
                <input class="form-control" type="search" placeholder="Search" id="search-input" aria-label="Search"
                       name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-success my-2"><i class="fas fa-search"></i></button>
            </form>
        </div>
        <div class="col-8" id="for-user">
            <div>
                <ul class="navbar-nav  navbar-expand" style="flex-flow: column;">

                    <li class="if-not-login d-flex">
                        {% if not current_user.is_authenticated %}

                            <div class="nav-item">
                                <a class="nav-link" href="/">Info</a>
                            </div>
                            <div class="nav-item reg col-sm-6 col-md-auto d-flex justify-content-center">
                                <a class="nav-link" href="/register">Регистрация</a>
                            </div>

                            <div class="nav-item log col-sm-6 col-md-auto d-flex justify-content-center">
                                <a class="nav-link" href="/login">Войти</a>
                            </div>
                        {% endif %}
                    </li>

                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <div class="d-flex" id="if-login">
                                <div class="nav-item">
                                    <a class="nav-link" href="/">Info</a>
                                </div>
                                <div class="nav-item logout  justify-content-center">
                                    <a class="nav-link" href="/logout">Выйти</a>
                                </div>
                                <div class="nav-item home  justify-content-center">
                                    <a class="nav-link" href="/home">Профиль</a>
                                </div>
                            </div>
                        </li>

                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="col-4 d-flex justify-content-end" id="toggler">
            <button class="navbar-toggler col-sm-auto" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.index') }}">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.index') }}">Посты</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('posts.create_post') }}">Создать пост</a>
                    </li>
                {% endif %}
        </div>
    </div>


</nav>


{#------------------------------------------------------------------------------#}

<nav class="navbar navbar-dark for-all">
    <div class="row flex-grow-1" id="main-menu">
        <div class="icon-title d-flex col-sm-4 col-md-2 col-lg-2">
            <a class="navbar-brand mr-auto " href="/posts" style="color: #15acc5;">
                {#                    <img src="{{ url_for('static', filename='img/icons/ArtStart.svg') }}"#}
                {#                         class="img-fluid" alt="" style="height: 80px;">#}
                ArtStart
            </a>
        </div>

        <div class="col-sm-4 col-md-4 col-lg-5 col-xl-6" id="search">
            <form class="form d-flex align-items-center">
                <input class="form-control" type="search" placeholder="Search" id="search-input" aria-label="Search"
                       name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-success my-2"><i class="fas fa-search"></i></button>
            </form>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-3 col-xl-3" id="for-user">
            <div>
                <ul class="navbar-nav  navbar-expand" style="flex-flow: column;">

                    <li class="if-not-login d-flex">
                        {% if not current_user.is_authenticated %}
                            <div class="nav-item log col-sm-6 col-md-auto d-flex justify-content-center">
                                <a class="nav-link" href="/login">Войти</a>
                            </div>
                            <div class="nav-item reg col-sm-6 col-md-auto d-flex justify-content-center">
                                <a class="nav-link" href="/register">Регистрация</a>
                            </div>
                            <div class="nav-item">
                                <a class="nav-link" href="/">Info</a>
                            </div>
                        {% endif %}
                    </li>

                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <div class="d-flex" id="if-login">
                                <div class="nav-item home  justify-content-center">
                                    <a class="nav-link" href="/home">Профиль</a>
                                </div>
                                <div class="nav-item logout  justify-content-center">
                                    <a class="nav-link" href="/logout">Выйти</a>
                                </div>
                                <div class="nav-item">
                                    <a class="nav-link" href="/">Info</a>
                                </div>
                            </div>
                        </li>

                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="col-sm-4 col-md-2 col-lg-2 col-xl-1 pr-md-3 d-flex justify-content-end" id="toggler">
            <button class="navbar-toggler col-sm-auto" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.index') }}">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.index') }}">Посты</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('posts.create_post') }}">Создать пост</a>
                    </li>
                {% endif %}
        </div>
    </div>
</nav>


<div class="container-fluid">


    <h1>
        {% block content_title %}

        {% endblock %}
    </h1>


    {% block content %}

    {% endblock %}


</div>
<script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

{#<script src="{{ url_for('static', filename='js/imagesloaded.pkgd.js') }}"></script>#}
{#<script src="{{ url_for('static', filename='js/jquery-imagefill.js') }}"></script>#}

{#<script src="{{ url_for('static', filename='js/masonry.pkgd.js') }}"></script>#}


{#<script src="{{ url_for('static', filename='js/jcrop.js') }}"></script>#}
<script src="{{ url_for('static', filename='js/common.js') }}"></script>
<div class="clear" style="width:auto; height: 250px;"></div>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    О сайте
{% endblock %}



{% block content_title %}
    О сайте
{% endblock %}

{% block content %}
{{message}}Сайт для художников и дизайнеров различных сфер.<br>
<p>Для разработки задействован микро-фреймворк Flask для бэкенда и Bootstrap 4 для фронтенда.</p>
{% endblock %}    

users/templates/users/index.html
{% extends 'base.html' %}

{% block title %}
    Пользователи
{% endblock %}

{% block content_title %}
    Пользователи
{% endblock %}
    
{% block content %}
    Пользователи
    {% for u in users %}
        <div class="">
            <a href="{{ url_for('users.user_profile', slug = u.slug) }}">{{ u.nickname }}</a>
        </div>
    {% endfor %} 
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Log in
{% endblock %}

{% block content_title %}
    Log in
{% endblock %}
    
{% block content %}
    <form action="{{ url_for('login') }}" method="POST" enctype="multipart/form-data">
        <input type="text" name="login" class="form-group form-control" placeholder="Your nickname" required>
        <input type="password" name="password" class="form-group form-control" placeholder="Your password" required>
        <p><input type="checkbox" name="remember">Remember me</p><br>
        <button class="btn btn-success" type=submit value=Login>Log in</button>
    </form>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block title %}
    User
{% endblock %}

{% block content_title %}
    User
{% endblock %}
    
{% block content %}
    <div class="">
        {{user_profile.nickname}}
    </div>
{% endblock %}

users/templates/users/user_profile_edit.html
{% extends 'base.html' %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block content_title %}
    Редактирование профиля
{% endblock %}

{% block content %}

    <form action="{{ url_for('edit_profile') }}" method="POST" enctype="multipart/form-data">
        <div class="avatar">
            <label>Изменить аватар</label>
            <div>
                <input type="file" name="avatar">
            </div>
        </div>
        <div class="description mt-4 mb-4">
            <label>Изменить описание профиля</label>
            <div>
                <textarea name="description" id="description" cols="60" rows="5"></textarea>
            </div>
        </div>
        <button class="btn btn-success" type="submit">Применить изменения</button>
    </form>

{% endblock %}

users/templates/users/user_profile_home.html
{% extends 'base.html' %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block content_title %}
    Профиль пользователя
{% endblock %}

{% block content %}
    <div class="row">
        <div class="profile col-5">
            <div class="username">
                <h2>{{ user_profile.nickname }}</h2>
            </div>

            <div class="avatar m-3">
                {% for i in avatar %}
                    <img src="{{ url_for('static', filename='img/avatars/' + i.name) }}" class="rounded-circle"
                         style="width: 200px;">
                {% endfor %}
            </div>

            <div class="p-2 pb-4 col-7">
                <form action="{{ url_for('edit_profile') }}">
                    <button class="btn btn-success" type="submit">Редактировать профиль</button>
                </form>
            </div>
        </div>

        <div class="profile-description">
            <h5>{{ user_profile.description }}</h5>
        </div>
    </div>
    <div class="mb-3"><h3>Посты пользователя:</h3></div>
    <div class="works pt-4" style="border-top: 1px solid #9a9a9a;">
        <div class="row" style="padding: 0px 20px;">
            <div class="card-columns">
                {% for post in user_posts %}
                    <a href="{{ url_for('posts.post_detail', id = post.id) }}">
                        {% for i in post.pictures %}
                            <div class="card">
                                <img src="{{ url_for('static', filename='img/post_prev/' +  i.name) }}" class="img-fluid">
                            </div>
                        {% endfor %}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content_title %}
    Register
{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('reg_user') }}" method="POST" enctype="multipart/form-data">
        <input type="text" class="form-group form-control" placeholder="Enter nickname" name="nickname">
        <input type="text" class="form-group form-control" placeholder="Enter e-mail" name="email">
        <input type="password" class="form-group form-control" placeholder="Enter password" name="password">
        <input type="password" class="form-group form-control" placeholder="Confirm password" name="confirm_password">
        <button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}